### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 76

### ISSUE THREAD

**Issue by arzola** [lbausch/laravel-ci#10]
Hello Thank you for your Laravel docker Image I have been using this with bitbucket and this week stooped working,  these are my steps:

```
 #Install Functional Testing Tools
          - php artisan dusk:install
          - php artisan dusk:chrome-driver 76
          - rm ./tests/Browser/ExampleTest.php #Removing scaffolding test

          #Run Server
          - php artisan serve &
          - sleep 5
          #Run Functional tests suite
          - php artisan dusk
```

And I am getting `This version of ChromeDriver only supports Chrome version 76` do you have any clue?

**Comment by arzola** [comment]
Update:

It seems debian updated the default chromium version to 79 so I updated this line and it worked

`- php artisan dusk:chrome-driver 79`

**Comment by lbausch** [comment]
Glad you figured it out. You can protect yourself against surprises like this, if you use the provided tags instead of `latest`.
